### ISSUE TITLE
A bunch of page formatting and filtering tweaks.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/torque-sites#46]
These came from Jeff in an email -- recording them here to make it easier for you to just run down the checklist, @frankduncan.

* [x] no need to show the Title twice
* [x] show Description in sidebar summary (this is really part of issue #44)
* [x] group Primary Area of Expertise, Priority Populations, Primary Subject Area, Sustainable Development Goals, and Key Words together
* [x] remove Category ID and Subject Area ID fields (i.e., sec_map should just not include them)
* [x] put Bibliography at or near the end
* [x] Grouping Contact Info make sense, but it seems to be inserted now between “Total Resource Requirements” and some subheads under that topic.
* [ ] Consolidate Current Solution Countries and Future Work Countries sections.  Presumably, this means put them together in one overall section (but see email thread with Jeff in case he says "consolidate" actually means something else).
* [x] Include Annual operating budget and Number of Employees in sidebar (part of issue #44)
* [x] Put "Why Your Team" and "Key Staff" together
* [x] Links to the attached files can go in the sidebar (see issue #44 re sidebar).   Save this for last, as we haven't actually got attached files in the wiki at all yet (although the older system did this, and we need to get it working again).

Also, this isn't a formatting tweak, but it still needs to get done:

* [x] There's a particular application that's all in Arabic that came through as all question marks in the CSV we got (I think it's application 7322; no further identifying information should be given here, obviously).  The conversion pipeline should just filter it out.  The application is actually not valid anyway.  This really belongs in a separate issue, of course, but I'm in a hurry right now and didn't want to drop it on the floor.

**Comment by frankduncan** [comment]
I believe all of these are handled except the consolidation question.

**Comment by kfogel** [comment]
This is clearly done.  Closing.
